# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data
# files feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.


# Theme Configuration
# --------------------------------------------------
# Anything defined here can be accessed by templates under the `site` variable.
# Our theme permits or requires these settings.
# https://github.com/broccolini/swiss

title: CSIP @ UGA
description: Computer Science Interview Prep - Tuesdays @ 7:00pm, virtually through Discord
url: "https://csip-uga.github.io"  # TODO: Switch to csip.uga.edu (#1)
theme_color: black  # black, blue, gray, magenta, orange, red, white, or yellow.
github_username: csip-uga
github_repo: ""
# social_link: twitter  # twitter, instagram, medium, or dribbble.
# social_username: csip-uga


# Global Configuration
# --------------------------------------------------
# The options affect how Jekyll builds the site.
# https://jekyllrb.com/docs/configuration/

timezone: America/New_York  # Cannonical name for US/Eastern.
encoding: utf-8  # Must match the <meta charset> tag in the <head> of all pages.
baseurl: ""  # Empty string to use the domain's root.
markdown: kramdown  # Rendering engine.

# Pages blonging to the `foo` collection live in the `_foo` directory.
# https://jekyllrb.com/docs/collections/
collections:
  problems:
    output: true
    permalink: /problems/:path
  challenges:
    output: true
    permalink: /challenges/:path

# Front matter defaults.
# https://jekyllrb.com/docs/configuration/front-matter-defaults/
defaults:
  -
    scope:
      type: pages
    values:
      layout: page
      weight: 50
  -
    scope:
      type: posts
    values:
      layout: post
  -
    scope:
      type: problems
    values:
      layout: post
  -
    scope:
      type: challenges
    values:
      layout: post


# Plugins
# --------------------------------------------------
# GitHub Pages supports a limited number of plugins. A few are always enabled,
# however you should explicitly list and plugin you use for portability.
# https://help.github.com/articles/configuring-jekyll-plugins/

plugins:
   - jekyll-mentions

# The jekyll-mentions plugin turns `@username` into a link.
# https://github.com/jekyll/jekyll-mentions
jekyll-mentions:
  base_url: https://github.com
